title: "Mini-curso 03 — Comunicação I2C: Displays LCD e OLED"
description: "Sistemas Embarcados • Curso Técnico em Automação Industrial • MicroPython + ESP32 + Wokwi"
theme: jekyll-theme-cayman
show_downloads: false
